### ISSUE TITLE
Publish to CRAN

### ISSUE THREAD

**Issue by colinpmillar** [Faskally/ef#4]
## Tasks

- [ ] split package into RNS and ef #5
- [ ] check all documentation
- [ ] run CRAN checks
- [ ] tag version and release on github

## Depends on

'Split ef and RNS into two packages' #5
